-- local map = vim.keymap.set
-- local g = vim.g
-- g.mapleader = ","
-- local ls = require("luasnip")
-- require("luasnip.loaders.from_snipmate").lazy_load({ paths = { "/home/k.mikami/.local/share/nvim/lazy/vim-snippets/snippets/python.snippets" } })
-- map({ "i" }, "<C-k>", function() ls.expand() end, { silent = true })
-- map({ "i", "s" }, "<C-k>", function() ls.jump(1) end, { silent = true })
-- map({ "i", "s" }, "<C-j>", function() ls.jump(-1) end, { silent = true })
-- map({ "i", "s" }, "<C-E>", function()
--     if ls.choice_active() then
--         ls.change_choice(1)
--     end
-- end, { silent = true })
